### ISSUE TITLE
A problem to in-mem graph.

### ISSUE THREAD

**Issue by RichardWang11** [zilliztech/starling#30]
What if the sample data points not include different blocks in my selected segment? e.g. 12,0 for block 0 and 1 for block 2, then in-mem graph like 12-0-1, then I start from vertex 0, then 14 ... at this situation, it seems in-mem graph is not good enough. Hope you give a simple explaination on this, Thx!

**Comment by PwzXxm** [comment]
You could play with how you sample points to form the In-Memory Graph, i.e., you could
- Sample a single point from each block, or less
- Sample based on the visited frequency from search using sampled queries

The purpose of a In-Memory Graph is to provide a guidance of the direction on where the query should go, to reduce the Disk I/Os. I wouldn't say it is a "problem" since even if the desired points are not included in the In-Memory Graph, they are still reachable on the Disk Graph. You could imagine the In-Memory Graph is acting like a cache and by searching on it we can obtain a better entry point when we starting searching on the Disk.

**Comment by RichardWang11** [comment]
OK, thanks, it help me solve the confusion.
